[general]
import = [
  "catppuccin-macchiato.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
dynamic_title = true

[font]
normal = { family = "Monofur Nerd Font Mono", style = "Regular"}
bold = { style = "Bold"}
size = 13.50

[terminal]
shell = "pwsh"
